export default Object.freeze({
    a: '(emphasis)',
    kin: '(emphasis)',
    akesi: 'non-cute animal',
    ala: 'no',
    alasa: 'to hunt',
    ale: 'countless',
    ali: 'countless',
    anpa: 'bowing down',
    ante: 'altered',
    anu: 'or',
    awen: 'enduring',
    e: '(before direct object)',
    en: '(between multiple subjects)',
    esun: 'market',
    ijo: 'thing',
    ike: 'bad',
    ilo: 'tool',
    insa: 'centre',
    jaki: 'disgusting',
    jan: 'person',
    jelo: 'yellow',
    jo: 'to have',
    kala: 'sea creature',
    kalama: 'to produce a sound',
    kama: 'to become',
    kasi: 'vegetation',
    ken: 'to be able to',
    kepeken: 'to use',
    kili: 'fruit',
    kiwen: 'hard object',
    ko: 'clay',
    kon: 'spirit',
    kule: 'colorful',
    kulupu: 'community',
    kute: 'to hear',
    la: '(between context phrase and main sentence)',
    lape: 'sleeping',
    laso: 'blue-green',
    lawa: 'to control',
    len: 'cloth',
    lete: 'cold',
    li: '(between subject and verb)',
    lili: 'little',
    linja: 'long and flexible thing',
    lipu: 'document',
    loje: 'red',
    lon: 'present at',
    luka: 'hand',
    lukin: 'to look at',
    oko: 'to look at',
    lupa: 'door',
    ma: 'earth',
    mama: 'ancestor',
    mani: 'money',
    meli: 'woman',
    mi: 'me',
    mije: 'man',
    moku: 'to eat',
    moli: 'dead',
    monsi: 'back',
    mu: '(animal communication)',
    mun: 'moon',
    musi: 'playful',
    mute: 'many',
    nanpa: 'numbered',
    nasa: 'strange',
    nasin: 'way',
    nena: 'bump',
    ni: 'this',
    nimi: 'name',
    noka: 'foot',
    o: 'hey!',
    olin: 'to love',
    ona: 'they',
    open: 'to begin',
    pakala: 'damaged',
    pali: 'to make',
    palisa: 'stick',
    pan: 'cereal',
    pana: 'to give',
    pi: 'of',
    pilin: 'heart',
    pimeja: 'dark',
    pini: 'finished',
    pipi: 'bug',
    poka: 'side',
    poki: 'container',
    pona: 'good',
    pu: 'interacting with the official Toki Pona book',
    sama: 'like',
    seli: 'fire',
    selo: 'outer layer',
    seme: 'what',
    sewi: 'super',
    sijelo: 'body of',
    sike: 'round thing',
    sin: 'new',
    namako: 'new',
    sina: 'you',
    sinpin: 'face',
    sitelen: 'image',
    sona: 'to know',
    soweli: 'animal',
    suli: 'big',
    suno: 'sun',
    supa: 'horizontal surface',
    suwi: 'sweet',
    tan: 'by',
    taso: 'but',
    tawa: 'toward',
    telo: 'water',
    tenpo: 'time',
    toki: 'to communicate',
    tomo: 'home',
    tu: 'two',
    unpa: 'to have sexual relations with',
    uta: 'mouth',
    utala: 'to battle',
    walo: 'pale',
    wan: 'one',
    waso: 'bird',
    wawa: 'strong',
    weka: 'away',
    wile: 'wish',
});
